# CSCN8000 – Artificial Intelligence Algorithms and Mathematics

## Lab 1: Basic NumPy Operations

### Student_Name = Sumit, Student ID: 8977542
<mark>Part A- Create a Notebook to demonstrate NumPy Operations.</mark>

### Q1. Create an array that starts from the integer 1, ends at 20, incremented by 3.

<mark>Comments</mark> : created an array ( starting  point is 1 : end point is 20 : step size 3)

In [56]:
array = list(range(1, 20, 3))
print(array)


[1, 4, 7, 10, 13, 16, 19]


### Q2. Create a new array of shape (3,) with random numbers between 0 and 1

<mark>Comments</mark> : Random array is generated range between 0 to 1 (3 numbers only)

In [57]:
import numpy as np
array1 = np.random.rand(3)

print(array1)


[0.3366884  0.9941061  0.28371851]


### Q3. Create a 2 D array [[10,20,45],[30,12,16],[42,17,56]] and perform the following operations: Slice the 2D array to get the first two rows, slice the 2D array to get the last two rows.

<mark>Comments</mark> : 

Step 1 : array is created 

step 2 : first and second row sliced out

step 3 : second and fouth row sliced out

step 4 : printing the sliced arrays

In [58]:
import numpy as np


array_2 = np.array([[10, 20, 45], [30, 12, 16], [42, 17, 56]])

# 1st and 2nd row
row1_2 = array_2[:2]

# 2nd and 3rd row
row2_3 = array_2[1:]

# Printing outputs
print("Original 2D array:")
print(array_2)
print("\nSliced array - 1st and 2nd row:")
print(row1_2)
print("\nSliced array - 2nd and 3rd row:")
print(row2_3)


Original 2D array:
[[10 20 45]
 [30 12 16]
 [42 17 56]]

Sliced array - 1st and 2nd row:
[[10 20 45]
 [30 12 16]]

Sliced array - 2nd and 3rd row:
[[30 12 16]
 [42 17 56]]


### Q4. Create two 2x2 arrays and demonstrate how you can stack the elements vertically, horizontally, and split the arrays into smaller arrays.

<mark>Comments</mark> : 

Step 1 : two array are created

Step 2 : use np.vstack for vertical stacking (both arrays)

step 3 : use np.h stack for horizontal stacking (both arrays)

step 4 : Spliting into two smaller groups vertically by using np.vsplit

step 5 : printng outputs

In [59]:
import numpy as np

# Create two 2x2 arrays
array1 = np.array([[1, 5], [3, 1]])
array2 = np.array([[4, 6], [7, 8]])

# Vertical stacking
vertical_stack = np.vstack((array1, array2))

# Horizontal stacking
horizontal_stack = np.hstack((array1, array2))

# Splitting into smaller arrays
vertical = np.vsplit(vertical_stack, 2)  
horizontal = np.hsplit(horizontal_stack, 2) 

print("Array 1:\n", array1)
print("\nArray 2:\n", array2)

print("\nVertical Stack:\n", vertical_stack)
print("\nHorizontal Stack:\n", horizontal_stack)

print("\nSplit Vertical:\n", vertical)
print("\nSplit Horizontal:\n", horizontal)


Array 1:
 [[1 5]
 [3 1]]

Array 2:
 [[4 6]
 [7 8]]

Vertical Stack:
 [[1 5]
 [3 1]
 [4 6]
 [7 8]]

Horizontal Stack:
 [[1 5 4 6]
 [3 1 7 8]]

Split Vertical:
 [array([[1, 5],
       [3, 1]]), array([[4, 6],
       [7, 8]])]

Split Horizontal:
 [array([[1, 5],
       [3, 1]]), array([[4, 6],
       [7, 8]])]


### Q5.Create two matrices 𝑋= ([[5,7,2],[4,5,6],[7,4 ,2]]),𝑌= ([[4,2],[6,2],[4,2]]),

 ### operations : 
 
### 1. Is it possible to multiply these matrices? 
 
 ### 2. Demonstrate the case when it is not possible to.


<mark>Comments</mark> :

step 1 : creating X and Y matrices

step 2 : using if condition by checking shape that multiply is possible



In [60]:
import numpy as np

# Create matrices X and Y
X = np.array([[5, 7, 2], [4, 5, 6], [7, 4, 2]])
Y = np.array([[4, 2], [6, 2], [4, 2]])


print(X.shape)

# Checking multiplication is possible
if X.shape[1] == Y.shape[0]:
    # If possible, perform matrix multiplication
    result = np.dot(X, Y)
    print("Matrix Multiplication Result:\n", result)
else:
    print("Multiplication is not possible because column in X is not equal to  rows in Y.")

a = np.array([[1,2,5], [2,3,4]])
b = np.array([[2,2], [3,3]])

if a.shape[1] == b.shape[0]:
    # If possible, perform matrix multiplication
    result = np.dot(a, b)
    print("\nMatrix Multiplication Result:\n", result)
else:
    print("\nMultiplication is not possible because column in a is not equal to  rows in b.")



(3, 3)
Matrix Multiplication Result:
 [[70 28]
 [70 30]
 [60 26]]

Multiplication is not possible because column in a is not equal to  rows in b.


### Q6.Create two arrays, 𝑥 = ([2,−1,−8]) 𝑦 = ([3,1,−2]),
### operations :
### a.Find the Shape, Number of dimensions of vector x.

### b.Reshape the vector x to a matrix of size (3,1) and determine the number of dimensions after reshaping y to a matrix of (3,1).

<mark>Comments</mark> :

step 1 : creating X and Y array

step 2 : finding shape and dimentions of x vector using  x_shape and x_dimention

step 3 : reshaping of x to (3,1) using x_reshape then finding X dimention

step 4 : steps repeated for Y matrix

step 5 : printing outputs



In [61]:
import numpy as np

# Create two arrays x and y
x = np.array([2, -1, -8])
y = np.array([3, 1, -2])

# a. find Shape and Number  vector x
x_shape = x.shape
x_dimension = x.ndim

# b. Reshape x 
x_reshape = x.reshape((3, 1))
x_reshape_d = x_reshape.ndim

#  Reshape y 
y_reshaped = y.reshape((3, 1))
y_reshaped_d = y_reshaped.ndim

# Print results
print("a. Shape of vector x:", x_shape)
print("   Number of dimensions of vector x:", x_dimension)
print("\nb. Reshaped matrix of x :\n", x_reshape)
print("   dimensions after reshaping x:", x_reshape_d)
print("\n   Reshaped matrix of y :\n", y_reshaped)
print("   dimensions after reshaping y:", y_reshaped_d)


a. Shape of vector x: (3,)
   Number of dimensions of vector x: 1

b. Reshaped matrix of x :
 [[ 2]
 [-1]
 [-8]]
   dimensions after reshaping x: 2

   Reshaped matrix of y :
 [[ 3]
 [ 1]
 [-2]]
   dimensions after reshaping y: 2


### Q7.How does broadcasting work? Demonstrate the subtraction, multiplication by considering a 3 x 3 matrix.

Broadcasting : The idea behind broadcasting is to repeat the values of the smaller size matrix to make it appear as though it is the same as the larger one when we have two matrices of different forms. It is comparable to replicating the smaller matrix to match the larger one's dimensions. Even in cases where the matrices have different sizes, it enables us to perform the mathematical action.    

<mark>Comments</mark> :

step 1 : creating 3x3 matrix

step 2 : subtracting and multiplying array to 3x3 matrix 

step 3 : printing outputs

In [62]:
import numpy as np

#Matrix 1 (shape(3,3))

matrix = np.array([[7, 5, 3],
                   [4, 5, 6],
                   [7, 8, 9]])


#  1D array is subtracted and multiplied
subtract_array = np.array([4, 2, 3])
multiply_array = np.array([8, 5, 4])

# subtraction
subtraction = matrix - subtract_array

#  multiplication
multiplication = matrix * multiply_array

# Print the original matrix and the results
print("Matrix 3*3:\n", matrix)
print("\nSubtraction :\n", subtraction)
print("\nMultiplication :\n", multiplication)


Matrix 3*3:
 [[7 5 3]
 [4 5 6]
 [7 8 9]]

Subtraction :
 [[3 3 0]
 [0 3 3]
 [3 6 6]]

Multiplication :
 [[56 25 12]
 [32 25 24]
 [56 40 36]]


# Part B- Linear Equations

### Determine the singularity of the system of equations, comment on the expected solution of the system. Solve the system of equations if possible. Justify the reason why you believe the system can or cannot be solved using NumPy functions.

### Question 1 :

Part B.1

4x + y - 2z = 10

2x - 3y + 2z = -4

x + 2y + 3z = 6

<mark>Comments</mark> :

step 1 : arranging equation into matrix order

step 2 : Calculating Determinents by using np.linalg.det

step 3 : printing outputs  shows that the result is not zero then it is a <mark>non singular matrix</mark>

In [63]:
# Coefficients of equation 1
equation_1 = np.array([[4, 1, -2],
                      [2, -3, 2],
                      [1, 2, 3]])

# Calculating the determinant of equation 1
determinant_equation_1 = np.linalg.det(equation_1)

# Checking A is singular or non singular
is_singular = determinant_equation_1 == 0

print(f"determinent is{determinant_equation_1} , singular : {is_singular}")


determinent is-70.00000000000003 , singular : False


### Question 2 :

Part B.2 

2x - y + 3z + 4w = 10 

4x - 2y + 6z + 8w = 20 

3x + y - 2z + 2w = 3 

x + 3y - 4z + w = -1

<mark>Comments</mark> :

step 1 : arranging equation into matrix order

step 2 : Calculating Determinents by using np.linalg.det

step 3 : printing outputs  shows that the result is not zero then it is a <mark> singular matrix</mark>

In [64]:
# Coefficients of equation 2
equation_2 = np.array([[2, -1, 3, 4],
               [4, -2, 6, 8],
               [3, 1, -2, 2],
               [1, 3, -4, 1]])

# Calculating the determinant of equation 2
determinant_equation = np.linalg.det(equation_2)

# Checkinging A is singular or non singular
is_singular2 = determinant_equation == 0

print(f"determinent is {determinant_equation} , singular : {is_singular2}")


determinent is 0.0 , singular : True
